-- cndemo_document_ai_docs
DROP TABLE CNDEMO_DOCUMENT_AI_DOCS;
CREATE TABLE CNDEMO_DOCUMENT_AI_DOCS
(document_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT CNDEMO_DOCUMENT_AI_DOCS_PK PRIMARY KEY NOT NULL
,file_name           VARCHAR2(100)  NOT NULL
,mime_type           VARCHAR2(100)  NOT NULL
,object_store_url    VARCHAR2(1000) NOT NULL
,doc_ai_json         CLOB
,language_code       VARCHAR2(10)
,language_score      NUMBER
,document_type_code  VARCHAR2(50)
,document_type_score NUMBER
,page_count          NUMBER
,status_code         VARCHAR2(25) DEFAULT ON NULL 'WIP'
,creation_date       TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
,created_by          VARCHAR2(255) NOT NULL
,last_update_date    TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
,last_updated_by     VARCHAR2(255) NOT NULL);

-- Trigger to handle record history fields.
CREATE OR REPLACE EDITIONABLE TRIGGER CNDEMO_DOCUMENT_AI_DOCS_BIU
BEFORE INSERT OR UPDATE ON CNDEMO_DOCUMENT_AI_DOCS FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :new.created_by       := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'),SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :new.creation_date    := current_timestamp;
    :new.last_updated_by  := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'),SYS_CONTEXT('USERENV', 'SESSION_USER'));
    :new.last_update_date := current_timestamp;
  ELSIF UPDATING THEN
    :new.last_updated_by  := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :new.last_update_date := current_timestamp;
  END IF;
END;
/
