-- Table Name: cn_ms_graph_opts
DROP TABLE CN_MS_GRAPH_OPTS;
CREATE TABLE CN_MS_GRAPH_OPTS
 (option_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT CN_MS_GRAPH_OPTS_PK PRIMARY KEY NOT NULL,
  option_code       VARCHAR2(30)   NOT NULL,
  option_value      VARCHAR2(4000) NOT NULL,
  description       VARCHAR2(500),
  creation_date     TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL,
  created_by        VARCHAR2(255) NOT NULL,
  last_update_date  TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL,
  last_updated_by   VARCHAR2(255) NOT NULL);

CREATE UNIQUE INDEX CN_MS_GRAPH_OPTS_U1 ON CN_MS_GRAPH_OPTS (option_code);

CREATE OR REPLACE EDITIONABLE TRIGGER CN_MS_GRAPH_OPTS 
   BEFORE INSERT OR UPDATE ON CN_MS_GRAPH_OPTS FOR EACH ROW
BEGIN
  IF INSERTING THEN
    :new.CREATED_BY       := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :new.CREATION_DATE    := current_timestamp;
    :new.LAST_UPDATED_BY  := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :new.LAST_UPDATE_DATE := current_timestamp;
  ELSIF UPDATING THEN
    :new.LAST_UPDATED_BY  := COALESCE(SYS_CONTEXT('APEX$SESSION','APP_USER'),USER);
    :new.LAST_UPDATE_DATE := current_timestamp;
  END IF;
END;
/

-- Create Template Records.
INSERT INTO CN_MS_GRAPH_OPTS (option_code, option_value, description)
  VALUES ('TENANT_ID', 'TBD', 'Microsoft Office 365 Tenant ID');
INSERT INTO CN_MS_GRAPH_OPTS (option_code, option_value, description)
  VALUES ('AUTH_TOKEN_URL', 'https://login.microsoftonline.com/#TENANTID#/oauth2/v2.0/token', 'URL used to get an Auth Token from Microsoft.');
INSERT INTO CN_MS_GRAPH_OPTS (option_code, option_value, description)
  VALUES ('WEB_CREDENTIAL_STATIC_ID', 'MS_OFFICE365_INTEGRATION_BLOG', 'Web credential with Access to Office 365 Services.');

INSERT INTO CN_MS_GRAPH_OPTS (option_code, option_value, description)
  VALUES ('EMAIL_ATTACHMENT_ENDPOINT', 'https://graph.microsoft.com/v1.0/users/#USER_ID#/mailFolders/Inbox/messages/#MESSAGE_ID#/attachments/#ATTACHMENT_ID#/$value', 'MS Graph Endpoint to get a Specific Email Attachment.');

COMMIT;